### ISSUE TITLE
Cannot find module 'babel-runtime/core-js/json/stringify'

### ISSUE THREAD

**Issue by sgregson** [IonicaBizau/ajs#23]
(npm@4.0.5 // node@v6.9.4 // nvm@0.32.0)

When running :

> $ git-stats-html

I'm getting this error `Error: Cannot find module 'babel-runtime/core-js/json/stringify'`

***

It seems like this is the same issue `gulp-babel` was facing with https://github.com/babel/gulp-babel/issues/50#issuecomment-256124142. I'll try to make a local clone and `npm link` to test `npm install --save babel-runtime` as they recommend.

Full trace:
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/json/stringify'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sgregson/.nvm/versions/node/v6.9.4/lib/node_modules/git-stats-html/node_modules/ajs/lib/index.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by IonicaBizau** [comment]
I hope it's fine now.

**Comment by mbm56767** [comment]
By installing babel-runtime as dependency i was able to fix the issue.
